apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-openshift-acs-clusters
  namespace: acs-install-policies
spec:
  clusterSelector:
    matchExpressions:
    - key: vendor
      values:
      - OpenShift
    - key: name
      operator: In
      values:
      - development
