apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-openshift-acs-hub
  namespace: acs-install-policies
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster
