apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-acs-install
placementBindingDefaults:
  name: acs-install-binding
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: acm-install-policies
  policySets:
    - openshift-acm-hub
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
# ACS Policies - start
- name: policy-acs-operator-central
  categories:
    - SC System and Communications Protection
  controls: 
    - SC-1 Policy and Procedures
  manifests:
    - path: acs-central/policy-acs-operator-central.yaml

- name: policy-acs-central-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-5 Security Alerts Advisories and Directives
  dependencies:
    - name: policy-acs-operator-central
  manifests:
    - path: acs-central/policy-acs-central-status.yaml
  remediationAction: inform

- name: policy-acs-central-ca-bundle
  categories:
    - SI System and Information Integrity
  consolidateManifests: false
  controls:
    - SI-5 Security Alerts Advisories and Directives
  dependencies:
    - name: policy-acs-central-status
  manifests:
    - path: acs-secured/policy-acs-central-ca-bundle.yaml
    - path: acs-secured/policy-acs-central-ca-bundle-v2.yaml
    - path: acs-secured/policy-acs-central-ca-bundle-v1.yaml
      complianceType: mustnothave

- name: policy-acs-sync-resources
  categories:
    - SI System and Information Integrity
  consolidateManifests: false
  controls:
    - SI-5 Security Alerts Advisories and Directives
  dependencies:
    - name: policy-acs-central-ca-bundle
  manifests:
    - path: acs-secured/policy-acs-sync-resources.yaml

- name: policy-acs-monitor-certs
  categories:
    - SC System and Communications Protection
  consolidateManifests: false
  controls:
    - SC-8 Transmission Confidentiality and Integrity
  dependencies:
    - name: policy-acs-central-ca-bundle
  manifests:
    - path: acs-secured/acs-check-certificates.yaml
    - path: acs-secured/policy-acs-central-ca-bundle-expired.yaml
      remediationAction: inform

- name: policy-acs-central-ca-bundle-expired
  categories:
    - SC System and Communications Protection
  consolidateManifests: false
  complianceType: mustnothave
  controls:
    - SC-8 Transmission Confidentiality and Integrity
  dependencies:
    - name: policy-acs-monitor-certs
      compliance: "NonCompliant"
  policyAnnotations:
    policy.open-cluster-management.io/description: 'Policy will remove expired certificates created by the init-bundle in policy policy-acs-central-ca-bundle so we can create a new init-bundle'
  evaluationInterval:
    compliant: 1m
    noncompliant: 45s
  ## ignorePending prevents the NotCompliant dependency from causing this policy to always report as pending
  ignorePending: true
  manifests:
    - path: acs-secured/policy-acs-central-ca-bundle-expired.yaml
    - path: acs-secured/policy-acs-central-ca-bundle-v2.yaml

- name: policy-advanced-managed-cluster-security
  categories:
    - SI System and Information Integrity
  consolidateManifests: false
  controls:
    - SI-5 Security Alerts Advisories and Directives
  manifests:
    - path: acs-secured/policy-advanced-managed-cluster-security.yaml
  policySets:
    - openshift-acm-clusters

- name: policy-advanced-managed-cluster-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-5 Security Alerts Advisories and Directives
  manifests:
    - path: acs-secured/policy-advanced-managed-cluster-status.yaml
  policySets:
    - openshift-acm-hub
    - openshift-acm-clusters
  remediationAction: inform
# ACS Policies - end
# Compliance Operator Policies - start
#- name: policy-compliance-operator-install
#  categories:
#    - CA Security Assessment and Authorization
#  controls:
#    - CA-2 Security Assessments
#    - CA-7 Continuous Monitoring
#  manifests:
#    - path: compliance-operator/policy-compliance-operator-install.yaml
#  policySets:
#    - openshift-acm-clusters
#    - openshift-acm-hub
# Compliance Operator Policies - end
policySets:
  - name: openshift-acm-hub
    description: The OpenShift ACS policy set applies several policies
      that will install the OpenShift Advanced Cluster Security using best practices. 
      This policy set is focused on the components that install to the Advanced Cluster Management hub.
    placement:
      placementRulePath: placements/hub-placement.yaml

  - name: openshift-acm-clusters
    description: The OpenShift ACS policy set applies several policies
      that will install the OpenShift Advanced Cluster Security using best practices. 
      This policy set is focused on the components that install to every managed cluster.
    placement:
      placementRulePath: placements/clusters-placement.yaml
