apiVersion: v1
kind: Namespace
metadata:
  name: acs-policies
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acs-policies
  namespace: acs-policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - acs-install-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: acs-install-policies
  namespace: acs-policies
spec:
  type: Git
  pathname: https://github.com/skylarscaling/acm-install-acs.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: kustomize
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acs-install-policies
  name: acs-install-policies-subscription
  namespace: acs-policies
spec:
  channel: acs-policies/acs-install-policies
  placement:
    placementRef:
      kind: PlacementRule
      name: acs-install-policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acs-install-policies
  name: acs-install-policies-placement
  namespace: acs-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"