apiVersion: policy.open-cluster-management.io/v1
kind: CertificatePolicy
metadata:
  name: acs-bundle-certificates
spec:
  namespaceSelector:
    include: ["acm-install-policies"]
  remediationAction: inform
  severity: high
  minimumDuration: 720h
