apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-openshift-acs-hub
  namespace: acs-install-policies
spec:
  clusterSelector:
    matchLabels:
        name: local-cluster