---
apiVersion: v1
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
---
apiVersion: v1
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
---
apiVersion: v1
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox